"""add ban fields to users

Revision ID: 3571381d8bdf
Revises: 484d6095f41f
Create Date: 2025-12-13 19:44:09.856182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3571381d8bdf'
down_revision: Union[str, Sequence[str], None] = '484d6095f41f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ban_reason', sa.String(), nullable=True))
    op.add_column('users', sa.Column('banned_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'banned_at')
    op.drop_column('users', 'ban_reason')
    # ### end Alembic commands ###
