"""add achievements table

Revision ID: e7dd7b826e7b
Revises: 3571381d8bdf
Create Date: 2025-12-14 13:49:35.541999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7dd7b826e7b'
down_revision: Union[str, Sequence[str], None] = '3571381d8bdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievements', sa.Column('code', sa.String(), nullable=False))
    op.add_column('achievements', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('achievements', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('achievements', 'earned_at')
    op.drop_column('achievements', 'achievement_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievements', sa.Column('achievement_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('achievements', sa.Column('earned_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('achievements', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('achievements', 'created_at')
    op.drop_column('achievements', 'code')
    # ### end Alembic commands ###
